name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod
      run_tests:
        description: "Run tests before deploy?"
        required: true
        default: "yes"
        type: choice
        options:
          - yes
          - no

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected options
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Run tests: ${{ github.event.inputs.run_tests }}"

      - name: Run tests
        if: ${{ github.event.inputs.run_tests == 'yes' }}
        run: echo "Running tests..."

      - name: Deploy to environment
        run: echo "Deploying to ${{ github.event.inputs.environment }}..."
